// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MealNewController from "./meal_new_controller"
application.register("meal-new", MealNewController)

import RecipeSearchController from "./recipe_search_controller"
application.register("recipe-search", RecipeSearchController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
