// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
// rails stimulus:manifest:update

import { application } from "./application"

import MealNewController from "./meal_new_controller"
application.register("meal-new", MealNewController)

import ProductsSearchController from "./products_search_controller"
application.register("products-search", ProductsSearchController)

import RecipeSearchController from "./recipe_search_controller"
application.register("recipe-search", RecipeSearchController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
